# Generated by Django 4.1.7 on 2023-04-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('number_id', models.CharField(max_length=50)),
                ('image', models.ImageField(max_length=2083, upload_to='img/%y')),
            ],
        ),
    ]
