# Generated by Django 4.1.7 on 2023-04-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contract_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='number_id',
        ),
    ]
