# Generated by Django 4.1.7 on 2023-04-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Contact',
        ),
    ]
